# -*- coding: utf-8 -*-
"""ForLoop.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S6BL4cVvx9xcZBJIZbaaOXwi0g7kdpjp
"""

for i in range(20):
  print(i)

